# -*- coding: utf-8 -*-
"""MCDM_COBE COBE (gpt)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FzQ7lAdd41NVMGSwt4tg4ON7MsMKObD-
"""

# ============================================================
# 1. IMPORT LIBRARY
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import spearmanr
from google.colab import files

plt.style.use('seaborn-v0_8-whitegrid')

# ============================================================
# 2. UPLOAD DATASET EXCEL
# ============================================================

uploaded = files.upload()
file_name = list(uploaded.keys())[0]

xls = pd.ExcelFile(file_name)
print("Sheet tersedia:")
print(xls.sheet_names)

# ============================================================
# 3. PARAMETER PENELITIAN
# ============================================================

years = ['2020', '2021', '2022', '2023', '2024']

criteria = [
    'CR', 'CAR', 'AR', 'ART', 'AT', 'ET', 'IT',
    'DAR', 'DER', 'PER', 'PBV',
    'ROA', 'ROE', 'NPM', 'GPM'
]

benefit_criteria = [
    'CR', 'CAR', 'AR', 'ART', 'AT', 'ET', 'IT',
    'ROA', 'ROE', 'NPM', 'GPM', 'PER', 'PBV'
]

cost_criteria = [
    'DAR', 'DER'
]

# ============================================================
# 4. WINSORIZATION / CAPPING
# ============================================================

def winsorize_iqr(df, cols, k=1.5):
    df_w = df.copy()
    bounds = []

    for col in cols:
        q1 = df_w[col].quantile(0.25)
        q3 = df_w[col].quantile(0.75)
        iqr = q3 - q1

        lower = q1 - k * iqr
        upper = q3 + k * iqr

        before = df_w[col].copy()
        df_w[col] = df_w[col].clip(lower=lower, upper=upper)

        changed = (before != df_w[col]).sum()

        bounds.append({
            'Kriteria': col,
            'Q1': q1,
            'Q3': q3,
            'IQR': iqr,
            'Lower_Bound': lower,
            'Upper_Bound': upper,
            'Jumlah_Dicapping': changed
        })

    return df_w, pd.DataFrame(bounds)

]=[# ============================================================
# 5. NORMALISASI MIN-MAX BENEFIT/COST
# ============================================================

def minmax_normalization(df, criteria, benefit_criteria, cost_criteria, eps=1e-12):
    norm = pd.DataFrame()
    norm['Kode'] = df['Kode']

    for col in criteria:
        x_min = df[col].min()
        x_max = df[col].max()

        if x_max == x_min:
            norm[col] = 1.0
        else:
            if col in benefit_criteria:
                norm[col] = (df[col] - x_min) / (x_max - x_min)
            elif col in cost_criteria:
                norm[col] = (x_max - df[col]) / (x_max - x_min)
            else:
                raise ValueError(f"Kriteria {col} belum masuk benefit/cost")

        norm[col] = norm[col] + eps

    return norm

# ============================================================
# 6. PEMBOBOTAN ENTROPY
# ============================================================

def entropy_weight(norm_df, criteria):
    X = norm_df[criteria].values.astype(float)

    P = X / X.sum(axis=0)

    m = X.shape[0]
    k = 1 / np.log(m)

    E = -k * np.sum(P * np.log(P), axis=0)
    D = 1 - E
    W = D / D.sum()

    weights = pd.DataFrame({
        'Kriteria': criteria,
        'Entropy': E,
        'Diversification': D,
        'Bobot': W
    })

    return weights

# ============================================================
# 7. TOPSIS DETAIL
# ============================================================

def topsis_detail(norm_df, criteria, weights):
    kode = norm_df['Kode'].values
    X = norm_df[criteria].values.astype(float)

    W = weights.set_index('Kriteria').loc[criteria, 'Bobot'].values

    # Matriks normalisasi terbobot
    V = X * W

    weighted_df = pd.DataFrame(V, columns=criteria)
    weighted_df.insert(0, 'Kode', kode)

    # Tabel 4: A+ dan A-
    A_plus = V.max(axis=0)
    A_minus = V.min(axis=0)

    table_4 = pd.DataFrame({
        'Solusi': ['A+', 'A-']
    })

    for i, col in enumerate(criteria):
        table_4[col] = [A_plus[i], A_minus[i]]

    # Tabel 5: jarak ke positive ideal D+
    D_plus = np.sqrt(((V - A_plus) ** 2).sum(axis=1))

    table_5 = pd.DataFrame({
        'Kode': kode,
        'D_plus': D_plus
    })

    table_5['D_plus_Rank'] = table_5['D_plus'].rank(
        ascending=True,
        method='dense'
    ).astype(int)

    # Tabel 6: jarak ke negative ideal D-
    D_minus = np.sqrt(((V - A_minus) ** 2).sum(axis=1))

    table_6 = pd.DataFrame({
        'Kode': kode,
        'D_minus': D_minus
    })

    table_6['D_minus_Rank'] = table_6['D_minus'].rank(
        ascending=False,
        method='dense'
    ).astype(int)

    # Tabel 7: proximity / closeness coefficient
    C_plus = D_minus / (D_plus + D_minus)

    table_7 = pd.DataFrame({
        'Kode': kode,
        'D_plus': D_plus,
        'D_minus': D_minus,
        'TOPSIS_Cplus': C_plus
    })

    table_7['TOPSIS_Rank'] = table_7['TOPSIS_Cplus'].rank(
        ascending=False,
        method='dense'
    ).astype(int)

    table_7 = table_7.sort_values('TOPSIS_Rank').reset_index(drop=True)

    return weighted_df, table_4, table_5, table_6, table_7

# ============================================================
# 8. VIKOR DETAIL
# ============================================================

def vikor_detail(norm_df, criteria, weights, v_values=[0.25, 0.50, 0.75, 1.00]):
    kode = norm_df['Kode'].values
    X = norm_df[criteria].values.astype(float)

    W = weights.set_index('Kriteria').loc[criteria, 'Bobot'].values

    f_star = X.max(axis=0)
    f_minus = X.min(axis=0)

    denom = f_star - f_minus
    denom[denom == 0] = 1e-12

    regret_matrix = W * ((f_star - X) / denom)

    S = regret_matrix.sum(axis=1)
    R = regret_matrix.max(axis=1)

    # Tabel 8: S, R, dan ranking
    table_8 = pd.DataFrame({
        'Kode': kode,
        'S': S,
        'S_Rank': pd.Series(S).rank(ascending=True, method='dense').astype(int),
        'R': R,
        'R_Rank': pd.Series(R).rank(ascending=True, method='dense').astype(int)
    })

    table_8 = table_8.sort_values('S_Rank').reset_index(drop=True)

    S_star, S_minus = S.min(), S.max()
    R_star, R_minus = R.min(), R.max()

    q_data = pd.DataFrame({'Kode': kode})

    for v in v_values:
        Q = (
            v * ((S - S_star) / (S_minus - S_star + 1e-12)) +
            (1 - v) * ((R - R_star) / (R_minus - R_star + 1e-12))
        )

        q_data[f'Q_v_{v:.2f}'] = Q
        q_data[f'Rank_v_{v:.2f}'] = pd.Series(Q).rank(
            ascending=True,
            method='dense'
        ).astype(int)

    # Tabel 9: Q untuk beberapa nilai v
    table_9 = q_data.copy()

    # Tabel utama VIKOR memakai v = 0.50
    main_col = 'Q_v_0.50'

    table_vikor_rank = table_9[['Kode', main_col, 'Rank_v_0.50']].copy()
    table_vikor_rank = table_vikor_rank.rename(columns={
        main_col: 'VIKOR_Q',
        'Rank_v_0.50': 'VIKOR_Rank'
    })
    table_vikor_rank = table_vikor_rank.sort_values('VIKOR_Rank').reset_index(drop=True)

    # Tabel 10: acceptable advantage
    table_10_rows = []

    m = len(kode)
    DQ = 1 / (m - 1)

    for v in v_values:
        q_col = f'Q_v_{v:.2f}'
        rank_col = f'Rank_v_{v:.2f}'

        temp = table_9[['Kode', q_col, rank_col]].copy()
        temp = temp.sort_values(q_col).reset_index(drop=True)

        best_alt = temp.loc[0, 'Kode']
        second_alt = temp.loc[1, 'Kode']

        q_best = temp.loc[0, q_col]
        q_second = temp.loc[1, q_col]

        q_diff = q_second - q_best
        acceptable_advantage = q_diff >= DQ

        table_10_rows.append({
            'v': v,
            'DQ': DQ,
            'Best_Alternative': best_alt,
            'Second_Alternative': second_alt,
            'Q_Best': q_best,
            'Q_Second': q_second,
            'Q_Second_minus_Q_Best': q_diff,
            'Acceptable_Advantage': acceptable_advantage
        })

    table_10 = pd.DataFrame(table_10_rows)

    return table_8, table_9, table_10, table_vikor_rank

# ============================================================
# 9. RUNNING ANALISIS SEMUA TAHUN
# ============================================================

all_results = {}
summary_rows = []
spearman_rows = []

for year in years:
    print(f"\n==================== {year} ====================")

    df = pd.read_excel(file_name, sheet_name=year)

    df.columns = df.columns.astype(str).str.strip()
    df['Kode'] = df['Kode'].astype(str).str.strip()

    df = df[['Kode'] + criteria].copy()

    for col in criteria:
        df[col] = pd.to_numeric(df[col], errors='coerce')

    if df[criteria].isna().sum().sum() > 0:
        print("Peringatan: terdapat missing value")
        print(df[criteria].isna().sum())

    # Winsorization
    df_winsor, winsor_bounds = winsorize_iqr(df, criteria, k=1.5)

    # Normalisasi
    df_norm = minmax_normalization(
        df_winsor,
        criteria,
        benefit_criteria,
        cost_criteria
    )

    # Entropy
    weights = entropy_weight(df_norm, criteria)

    # TOPSIS detail
    weighted_df, table_4, table_5, table_6, table_7 = topsis_detail(
        df_norm,
        criteria,
        weights
    )

    # VIKOR detail
    table_8, table_9, table_10, vikor_rank = vikor_detail(
        df_norm,
        criteria,
        weights,
    )

    # Gabungan ranking TOPSIS dan VIKOR
    final_rank = table_7[['Kode', 'TOPSIS_Cplus', 'TOPSIS_Rank']].merge(
        vikor_rank[['Kode', 'VIKOR_Q', 'VIKOR_Rank']],
        on='Kode',
        how='left'
    )

    # Spearman rank correlation
    rho, p_value = spearmanr(
        final_rank['TOPSIS_Rank'],
        final_rank['VIKOR_Rank']
    )

    final_rank['Spearman_Rho'] = rho
    final_rank['Spearman_P_Value'] = p_value

    spearman_rows.append({
        'Tahun': year,
        'Spearman_Rho': rho,
        'P_Value': p_value
    })

    for _, row in final_rank.iterrows():
        summary_rows.append({
            'Tahun': year,
            'Kode': row['Kode'],
            'TOPSIS_Cplus': row['TOPSIS_Cplus'],
            'TOPSIS_Rank': row['TOPSIS_Rank'],
            'VIKOR_Q': row['VIKOR_Q'],
            'VIKOR_Rank': row['VIKOR_Rank'],
            'Spearman_Rho': rho,
            'Spearman_P_Value': p_value
        })

    all_results[year] = {
        'Raw': df,
        'Winsorized': df_winsor,
        'Winsor_Bounds': winsor_bounds,
        'Normalized': df_norm,
        'Entropy_Weights': weights,
        'Weighted_Normalized': weighted_df,
        'Table_4_Ideal_Solutions': table_4,
        'Table_5_Dplus': table_5,
        'Table_6_Dminus': table_6,
        'Table_7_TOPSIS': table_7,
        'Table_8_VIKOR_SR': table_8,
        'Table_9_VIKOR_Q': table_9,
        'Table_10_VIKOR_Test': table_10,
        'Final_Ranking': final_rank
    }

    print("Bobot Entropy:")
    display(weights)

    print("Tabel 7 - Ranking TOPSIS:")
    display(table_7)

    print("Tabel 8 - S dan R VIKOR:")
    display(table_8)

    print("Tabel 9 - Q VIKOR:")
    display(table_9)

    print("Tabel 10 - Acceptable Advantage:")
    display(table_10)

    print("Final Ranking + Spearman:")
    display(final_rank)

summary_df = pd.DataFrame(summary_rows)
spearman_df = pd.DataFrame(spearman_rows)

# ============================================================
# 10. GRAFIK TOPSIS RANK 5 TAHUN
# ============================================================

plt.figure(figsize=(15, 8))

for kode in summary_df['Kode'].unique():
    temp = summary_df[summary_df['Kode'] == kode].sort_values('Tahun')

    plt.plot(
        temp['Tahun'],
        temp['TOPSIS_Rank'],
        marker='s',
        linewidth=1.8,
        label=kode
    )

plt.gca().invert_yaxis()
plt.title('Perkembangan Ranking TOPSIS Tahun 2020-2024')
plt.xlabel('Tahun')
plt.ylabel('Ranking')
plt.yticks(range(1, summary_df['TOPSIS_Rank'].max() + 1))
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.savefig('grafik_ranking_TOPSIS_2020_2024.png', dpi=300)
plt.show()

# ============================================================
# 11. GRAFIK VIKOR RANK 5 TAHUN
# ============================================================

plt.figure(figsize=(15, 8))

for kode in summary_df['Kode'].unique():
    temp = summary_df[summary_df['Kode'] == kode].sort_values('Tahun')

    plt.plot(
        temp['Tahun'],
        temp['VIKOR_Rank'],
        marker='s',
        linewidth=1.8,
        label=kode
    )

plt.gca().invert_yaxis()
plt.title('Perkembangan Ranking VIKOR Tahun 2020-2024')
plt.xlabel('Tahun')
plt.ylabel('Ranking')
plt.yticks(range(1, summary_df['VIKOR_Rank'].max() + 1))
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.savefig('grafik_ranking_vikor_2020_2024.png', dpi=300)
plt.show()

# ============================================================
# 12. GRAFIK GABUNGAN TOPSIS DAN VIKOR 5 TAHUN
# ============================================================

combined_plot = summary_df.copy()

plt.figure(figsize=(16, 9))

for kode in combined_plot['Kode'].unique():
    temp = combined_plot[combined_plot['Kode'] == kode].sort_values('Tahun')

    plt.plot(
        temp['Tahun'],
        temp['TOPSIS_Rank'],
        marker='o',
        linestyle='-',
        alpha=0.75,
        linewidth=1.5,
        label=f'{kode} - TOPSIS'
    )

    plt.plot(
        temp['Tahun'],
        temp['VIKOR_Rank'],
        marker='s',
        linestyle='--',
        alpha=0.75,
        linewidth=1.5,
        label=f'{kode} - VIKOR'
    )

plt.gca().invert_yaxis()
plt.title('Perbandingan Ranking TOPSIS dan VIKOR Tahun 2020-2024')
plt.xlabel('Tahun')
plt.ylabel('Ranking')
plt.yticks(range(1, summary_df[['TOPSIS_Rank', 'VIKOR_Rank']].max().max() + 1))
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', ncol=1, fontsize=8)
plt.tight_layout()
plt.savefig('grafik_perbandingan_topsis_vikor_2020_2024.png', dpi=300)
plt.show()

# ============================================================
# 13. GRAFIK ALTERNATIF: HEATMAP RANKING
# ============================================================

pivot_topsis = summary_df.pivot(index='Kode', columns='Tahun', values='TOPSIS_Rank')
pivot_vikor = summary_df.pivot(index='Kode', columns='Tahun', values='VIKOR_Rank')

plt.figure(figsize=(9, 7))
sns.heatmap(pivot_topsis, annot=True, fmt='.0f', cmap='RdYlGn_r')
plt.title('Heatmap Ranking TOPSIS 2020-2024')
plt.tight_layout()
plt.savefig('heatmap_ranking_topsis_2020_2024.png', dpi=300)
plt.show()

plt.figure(figsize=(9, 7))
sns.heatmap(pivot_vikor, annot=True, fmt='.0f', cmap='RdYlGn_r')
plt.title('Heatmap Ranking VIKOR 2020-2024')
plt.tight_layout()
plt.savefig('heatmap_ranking_vikor_2020_2024.png', dpi=300)
plt.show()

output_file = 'Hasil_Analisis_TOPSIS_VIKOR.xlsx'

# ============================================================
# 14. EXPORT HASIL KE EXCEL
# ============================================================

with pd.ExcelWriter(output_file, engine='openpyxl') as writer:
    summary_df.to_excel(writer, sheet_name='Summary_Ranking', index=False)
    spearman_df.to_excel(writer, sheet_name='Spearman', index=False)

    for year in years:
        all_results[year]['Raw'].to_excel(writer, sheet_name=f'Raw_{year}', index=False)
        all_results[year]['Winsorized'].to_excel(writer, sheet_name=f'Winsor_{year}', index=False)
        all_results[year]['Winsor_Bounds'].to_excel(writer, sheet_name=f'WinsorBound_{year}', index=False)
        all_results[year]['Normalized'].to_excel(writer, sheet_name=f'Norm_{year}', index=False)
        all_results[year]['Entropy_Weights'].to_excel(writer, sheet_name=f'Bobot_{year}', index=False)
        all_results[year]['Weighted_Normalized'].to_excel(writer, sheet_name=f'Terbobot_{year}', index=False)

        all_results[year]['Table_4_Ideal_Solutions'].to_excel(writer, sheet_name=f'Tabel4_{year}', index=False)
        all_results[year]['Table_5_Dplus'].to_excel(writer, sheet_name=f'Tabel5_{year}', index=False)
        all_results[year]['Table_6_Dminus'].to_excel(writer, sheet_name=f'Tabel6_{year}', index=False)
        all_results[year]['Table_7_TOPSIS'].to_excel(writer, sheet_name=f'Tabel7_{year}', index=False)

        all_results[year]['Table_8_VIKOR_SR'].to_excel(writer, sheet_name=f'Tabel8_{year}', index=False)
        all_results[year]['Table_9_VIKOR_Q'].to_excel(writer, sheet_name=f'Tabel9_{year}', index=False)
        all_results[year]['Table_10_VIKOR_Test'].to_excel(writer, sheet_name=f'Tabel10_{year}', index=False)

        all_results[year]['Final_Ranking'].to_excel(writer, sheet_name=f'FinalRank_{year}', index=False)

files.download(output_file)