# -*- coding: utf-8 -*-
"""MCDM TERBARU (codex)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fYDmKsyaBSVASzCs2Vz1A8RtTe8O7BLQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import spearmanr
from google.colab import files

uploaded = files.upload()

file_name = list(uploaded.keys())[0]
xls = pd.ExcelFile(file_name)

print("Sheet tersedia:")
print(xls.sheet_names)

# ============================================================
# 3. PARAMETER PENELITIAN
# ============================================================

years = ['2020', '2021', '2022', '2023', '2024']

criteria = [
    'CR', 'CAR', 'AR', 'ART', 'AT', 'ET', 'IT',
    'DAR', 'DER', 'PER', 'PBV',
    'ROA', 'ROE', 'NPM', 'GPM'
]

benefit_criteria = [
    'CR', 'CAR', 'AR', 'ART', 'AT', 'ET', 'IT',
    'ROA', 'ROE', 'NPM', 'GPM', 'PER', 'PBV'
]

cost_criteria = [
    'DAR', 'DER'
]

# ============================================================
# 4. FUNGSI WINSORIZATION / CAPPING
# ============================================================

def winsorize_iqr(df, cols, k=1.5):
    df_w = df.copy()
    bounds = {}

    for col in cols:
        q1 = df_w[col].quantile(0.25)
        q3 = df_w[col].quantile(0.75)
        iqr = q3 - q1

        lower = q1 - k * iqr
        upper = q3 + k * iqr

        bounds[col] = {
            'lower': lower,
            'upper': upper
        }

        df_w[col] = df_w[col].clip(lower=lower, upper=upper)

    return df_w, bounds

# ============================================================
# 5. NORMALISASI MIN-MAX UNTUK MCDM
# ============================================================

def minmax_normalization(df, criteria, benefit_criteria, cost_criteria, eps=1e-12):
    """
    Normalisasi min-max:
    Benefit = (x - min) / (max - min)
    Cost    = (max - x) / (max - min)

    Ditambah eps agar tidak ada nilai 0 untuk perhitungan entropy.
    """
    norm = pd.DataFrame()
    norm['Kode'] = df['Kode']

    for col in criteria:
        x_min = df[col].min()
        x_max = df[col].max()

        if x_max == x_min:
            norm[col] = 1
        else:
            if col in benefit_criteria:
                norm[col] = (df[col] - x_min) / (x_max - x_min)
            elif col in cost_criteria:
                norm[col] = (x_max - df[col]) / (x_max - x_min)
            else:
                raise ValueError(f"Kriteria {col} belum ditentukan sebagai benefit/cost")

        norm[col] = norm[col] + eps

    return norm

# ============================================================
# 6. PEMBOBOTAN ENTROPY
# ============================================================

def entropy_weight(norm_df, criteria):
    """
    Menghitung bobot entropy dari data yang sudah dinormalisasi positif.
    """
    X = norm_df[criteria].values.astype(float)

    # Proporsi tiap alternatif terhadap total kolom
    P = X / X.sum(axis=0)

    m = X.shape[0]
    k = 1 / np.log(m)

    # Entropy
    E = -k * np.sum(P * np.log(P), axis=0)

    # Degree of diversification
    D = 1 - E

    # Bobot
    W = D / D.sum()

    weights = pd.DataFrame({
        'Kriteria': criteria,
        'Entropy': E,
        'Diversification': D,
        'Bobot': W
    })

    return weights

# ============================================================
# 7. METODE TOPSIS
# ============================================================

def topsis(norm_df, criteria, weights):
    """
    TOPSIS menggunakan matriks normalisasi min-max yang sudah searah:
    semakin besar nilai normalisasi, semakin baik.
    """
    df_topsis = norm_df.copy()
    W = weights.set_index('Kriteria').loc[criteria, 'Bobot'].values

    X = df_topsis[criteria].values.astype(float)

    # Matriks ternormalisasi terbobot
    V = X * W

    ideal_positive = V.max(axis=0)
    ideal_negative = V.min(axis=0)

    d_positive = np.sqrt(((V - ideal_positive) ** 2).sum(axis=1))
    d_negative = np.sqrt(((V - ideal_negative) ** 2).sum(axis=1))

    preference = d_negative / (d_positive + d_negative)

    result = pd.DataFrame({
        'Kode': df_topsis['Kode'],
        'TOPSIS_Score': preference
    })

    result['TOPSIS_Rank'] = result['TOPSIS_Score'].rank(
        ascending=False,
        method='dense'
    ).astype(int)

    result = result.sort_values('TOPSIS_Rank').reset_index(drop=True)

    return result

# ============================================================
# 8. METODE VIKOR
# ============================================================

def vikor(norm_df, criteria, weights, v=0.5):
    """
    VIKOR menggunakan matriks normalisasi yang sudah searah:
    semakin besar nilai normalisasi, semakin baik.

    Pada VIKOR, Q terkecil adalah alternatif terbaik.
    """
    df_vikor = norm_df.copy()
    W = weights.set_index('Kriteria').loc[criteria, 'Bobot'].values

    X = df_vikor[criteria].values.astype(float)

    f_star = X.max(axis=0)
    f_minus = X.min(axis=0)

    denom = f_star - f_minus
    denom[denom == 0] = 1e-12

    regret_matrix = W * ((f_star - X) / denom)

    S = regret_matrix.sum(axis=1)
    R = regret_matrix.max(axis=1)

    S_star, S_minus = S.min(), S.max()
    R_star, R_minus = R.min(), R.max()

    Q = (
        v * ((S - S_star) / (S_minus - S_star + 1e-12)) +
        (1 - v) * ((R - R_star) / (R_minus - R_star + 1e-12))
    )

    result = pd.DataFrame({
        'Kode': df_vikor['Kode'],
        'S': S,
        'R': R,
        'VIKOR_Q': Q
    })

    result['VIKOR_Rank'] = result['VIKOR_Q'].rank(
        ascending=True,
        method='dense'
    ).astype(int)

    result = result.sort_values('VIKOR_Rank').reset_index(drop=True)

    return result

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import spearmanr
from google.colab import files

# ============================================================
# 9. RUNNING ANALISIS UNTUK SEMUA TAHUN
# ============================================================

all_results = {}
sn_df = []

for year in years:
    print(f"\n==================== {year} ====================")

    df = pd.read_excel(file_name, sheet_name=year)

    df.columns = df.columns.astype(str).str.strip()
    df['Kode'] = df['Kode'].astype(str).str.strip()

    # Ambil kolom yang digunakan
    df = df[['Kode'] + criteria].copy()

    # Pastikan numerik
    for col in criteria:
        df[col] = pd.to_numeric(df[col], errors='coerce')

    # Cek missing value
    if df[criteria].isna().sum().sum() > 0:
        print("Peringatan: ada missing value")
        print(df[criteria].isna().sum())

    # Winsorization / capping
    df_winsor, bounds = winsorize_iqr(df, criteria, k=1.5)

    # Normalisasi
    df_norm = minmax_normalization(
        df_winsor,
        criteria,
        benefit_criteria,
        cost_criteria
    )

    # Entropy weight
    weights = entropy_weight(df_norm, criteria)

    # TOPSIS
    topsis_result = topsis(df_norm, criteria, weights)

    # VIKOR
    vikor_result = vikor(df_norm, criteria, weights, v=0.5)

    # Gabungkan hasil
    final_result = topsis_result.merge(
        vikor_result,
        on='Kode',
        how='left'
    )

    # Spearman correlation
    rho, p_value = spearmanr(
        final_result['TOPSIS_Rank'],
        final_result['VIKOR_Rank']
    )

    final_result['Spearman_Rho'] = rho
    final_result['Spearman_P_Value'] = p_value

    all_results[year] = {
        'raw': df,
        'winsorized': df_winsor,
        'normalized': df_norm,
        'weights': weights,
        'ranking': final_result,
        'spearman_rho': rho,
        'spearman_p_value': p_value,
        'winsor_bounds': bounds
    }

    print("Bobot Entropy:")
    display(weights)

    print("Ranking TOPSIS dan VIKOR:")
    display(final_result)

    print(f"Spearman rho: {rho:.4f}")
    print(f"P-value: {p_value:.4f}")

    for _, row in final_result.iterrows():
        sn_df.append({
            'Tahun': year,
            'Kode': row['Kode'],
            'TOPSIS_Score': row['TOPSIS_Score'],
            'TOPSIS_Rank': row['TOPSIS_Rank'],
            'VIKOR_Q': row['VIKOR_Q'],
            'VIKOR_Rank': row['VIKOR_Rank'],
            'Spearman_Rho': rho,
            'Spearman_P_Value': p_value
        })

sn_df = pd.DataFrame(sn_df)

# ============================================================
# 10 VISUALISASI LINE CHART RANKING PER TAHUN
# ============================================================

for year in years:
    result = all_results[year]['ranking'].copy()

    # Urutkan berdasarkan ranking TOPSIS agar garis mudah dibaca
    result = result.sort_values('TOPSIS_Rank')

    plt.figure(figsize=(13, 6))

    plt.plot(
        result['Kode'],
        result['TOPSIS_Rank'],
        marker='o',
        linewidth=2,
        label='TOPSIS'
    )

    plt.plot(
        result['Kode'],
        result['VIKOR_Rank'],
        marker='s',
        linewidth=2,
        label='VIKOR'
    )

    plt.gca().invert_yaxis()

    plt.title(f'Perbandingan Ranking TOPSIS dan VIKOR Tahun {year}')
    plt.xlabel('Kode Emiten')
    plt.ylabel('Ranking')
    plt.xticks(rotation=45)
    plt.yticks(range(1, len(result) + 1))
    plt.grid(True, linestyle='--', alpha=0.4)
    plt.legend()
    plt.tight_layout()
    plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import spearmanr
from google.colab import files

# ============================================================
# 11 LINE CHART PERKEMBANGAN RANKING ANTAR TAHUN
# ============================================================

plt.figure(figsize=(14, 7))

for kode in sn_df['Kode'].unique():
    data_kode = sn_df[sn_df['Kode'] == kode]

    plt.plot(
        data_kode['Tahun'],
        data_kode['TOPSIS_Rank'],
        marker='o',
        linewidth=1.8,
        label=kode
    )

plt.gca().invert_yaxis()
plt.title('Perkembangan Ranking TOPSIS Tahun 2020-2024')
plt.xlabel('Tahun')
plt.ylabel('Ranking')
plt.yticks(range(1, sn_df['TOPSIS_Rank'].max() + 1))
plt.grid(True, linestyle='--', alpha=0.4)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

# ============================================================
# 12 LINE CHART PERKEMBANGAN RANKING ANTAR TAHUN
# ============================================================

plt.figure(figsize=(14, 7))

for kode in sn_df['Kode'].unique():
    data_kode = sn_df[sn_df['Kode'] == kode]

    plt.plot(
        data_kode['Tahun'],
        data_kode['VIKOR_Rank'],
        marker='o',
        linewidth=1.8,
        label=kode
    )

plt.gca().invert_yaxis()
plt.title('Perkembangan Ranking VIKOR Tahun 2020-2024')
plt.xlabel('Tahun')
plt.ylabel('Ranking')
plt.yticks(range(1, sn_df['VIKOR_Rank'].max() + 1))
plt.grid(True, linestyle='--', alpha=0.4)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

# ============================================================
# 13. TABEL SPEARMAN PER TAHUN
# ============================================================

spearman_summary = pd.DataFrame([
    {
        'Tahun': year,
        'Spearman_Rho': all_results[year]['spearman_rho'],
        'P_Value': all_results[year]['spearman_p_value']
    }
    for year in years
])

display(spearman_summary)

# ============================================================
# 13. EXPORT HASIL KE EXCEL
# ============================================================

output_file = 'hasil_mcdm_NEW_BGT.xlsx'

with pd.ExcelWriter(output_file, engine='openpyxl') as writer:
    sn_df.to_excel(writer, sheet_name='Summary_Ranking', index=False)
    spearman_summary.to_excel(writer, sheet_name='Spearman', index=False)

    for year in years:
        all_results[year]['weights'].to_excel(
            writer,
            sheet_name=f'Bobot_{year}',
            index=False
        )

        all_results[year]['ranking'].to_excel(
            writer,
            sheet_name=f'Ranking_{year}',
            index=False
        )

        all_results[year]['winsorized'].to_excel(
            writer,
            sheet_name=f'Winsor_{year}',
            index=False
        )

        all_results[year]['normalized'].to_excel(
            writer,
            sheet_name=f'Norm_{year}',
            index=False
        )

files.download(output_file)